version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: lb2_mysql
    environment:
      MYSQL_ROOT_PASSWORD: CsBe12345
      MYSQL_DATABASE: testdb
      MYSQL_USER: galihome
      MYSQL_PASSWORD: CsBe12345
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
  adminer_data: