version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: CsBe12345
      MYSQL_DATABASE: testdb
      MYSQL_USER: galihome
      MYSQL_PASSWORD: CsBe12345
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: